language: python
python:
  - "2.7"
  - "2.6"
  - "pypy"
install:
  - "pip install -e . coveralls --use-mirrors"
  - "yes http://salmon.local | salmon init test.conf"
script: coverage run --source=salmon $VIRTUAL_ENV/bin/salmon --config=test.conf test
after_success:
  - coveralls
